spring.application.name=control-escolar-api

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/control_escolar}
spring.datasource.username=${DB_USERNAME:sambarve}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

# Servidor
server.port=${SERVER_PORT:8080}

# Respuestas de error
spring.web.error.include-message=always
spring.web.error.include-stacktrace=never


# Firebase Cloud Messaging
app.firebase.enabled=${FIREBASE_ENABLED:false}
app.firebase.project-id=${FIREBASE_PROJECT_ID:}

# Notification delivery
app.notifications.delivery-enabled=${NOTIFICATION_DELIVERY_ENABLED:false}
app.notifications.delivery-delay-ms=${NOTIFICATION_DELIVERY_DELAY_MS:5000}