CREATE TABLE guardian_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id BIGINT NOT NULL UNIQUE,
    school_id BIGINT NOT NULL,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    activated_at TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_guardian_accounts_guardian
        FOREIGN KEY (guardian_id)
        REFERENCES guardians (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_guardian_accounts_school
        FOREIGN KEY (school_id)
        REFERENCES schools (id),

    CONSTRAINT chk_guardian_accounts_failed_attempts
        CHECK (failed_attempts >= 0)
);

CREATE UNIQUE INDEX uk_guardian_accounts_school_username_ci
    ON guardian_accounts (school_id, LOWER(username));

INSERT INTO guardian_accounts (
    guardian_id,
    school_id,
    username
)
SELECT
    guardian.id,
    guardian.school_id,
    CASE
        WHEN guardian.external_reference IS NOT NULL
             AND TRIM(guardian.external_reference) <> ''
            THEN UPPER(TRIM(guardian.external_reference))
        ELSE 'TUTOR-' || guardian.id || '-' ||
             UPPER(SUBSTRING(MD5(guardian.id::TEXT) FROM 1 FOR 6))
    END
FROM guardians guardian;

ALTER TABLE guardian_device_enrollments
    ADD COLUMN purpose VARCHAR(30) NOT NULL DEFAULT 'ACTIVATION';

ALTER TABLE guardian_device_enrollments
    ADD CONSTRAINT chk_guardian_device_enrollments_purpose
        CHECK (purpose IN ('ACTIVATION', 'PASSWORD_RESET'));

ALTER TABLE guardian_sessions
    ALTER COLUMN guardian_device_id DROP NOT NULL;
