CREATE TABLE school_communications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    category VARCHAR(30) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    audience_type VARCHAR(30) NOT NULL,
    audience_summary VARCHAR(500) NOT NULL,
    title VARCHAR(150) NOT NULL,
    message VARCHAR(4000) NOT NULL,
    requires_acknowledgement BOOLEAN NOT NULL DEFAULT FALSE,
    student_count INTEGER NOT NULL DEFAULT 0,
    recipient_count INTEGER NOT NULL DEFAULT 0,
    push_recipient_count INTEGER NOT NULL DEFAULT 0,
    scheduled_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_school_communications_school
        FOREIGN KEY (school_id) REFERENCES schools (id),
    CONSTRAINT fk_school_communications_created_by
        FOREIGN KEY (created_by) REFERENCES app_users (id),
    CONSTRAINT chk_school_communications_type
        CHECK (type IN ('GENERAL_NOTICE', 'EXPRESS_ALERT')),
    CONSTRAINT chk_school_communications_category
        CHECK (category IN ('GENERAL', 'SCHEDULE', 'ACADEMIC', 'EVENT', 'WEATHER', 'EMERGENCY', 'REMINDER', 'OTHER')),
    CONSTRAINT chk_school_communications_priority
        CHECK (priority IN ('NORMAL', 'IMPORTANT', 'URGENT')),
    CONSTRAINT chk_school_communications_status
        CHECK (status IN ('SCHEDULED', 'PUBLISHED', 'CANCELLED')),
    CONSTRAINT chk_school_communications_audience
        CHECK (audience_type IN ('ALL_SCHOOL', 'CYCLE', 'GRADES', 'GROUPS', 'STUDENTS'))
);

CREATE TABLE school_communication_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    communication_id BIGINT NOT NULL,
    guardian_id BIGINT NOT NULL,
    push_status VARCHAR(20) NOT NULL DEFAULT 'NOT_ENABLED',
    push_sent_at TIMESTAMPTZ,
    push_error VARCHAR(1000),
    viewed_at TIMESTAMPTZ,
    acknowledged_at TIMESTAMPTZ,

    CONSTRAINT fk_communication_recipients_communication
        FOREIGN KEY (communication_id)
        REFERENCES school_communications (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_communication_recipients_guardian
        FOREIGN KEY (guardian_id)
        REFERENCES guardians (id),
    CONSTRAINT uk_communication_recipient
        UNIQUE (communication_id, guardian_id),
    CONSTRAINT chk_communication_recipient_push_status
        CHECK (push_status IN ('NOT_ENABLED', 'PENDING', 'SENT', 'FAILED'))
);

ALTER TABLE notification_logs
    ALTER COLUMN access_event_id DROP NOT NULL;

ALTER TABLE notification_logs
    ADD COLUMN communication_recipient_id BIGINT;

ALTER TABLE notification_logs
    ADD CONSTRAINT fk_notification_logs_communication_recipient
        FOREIGN KEY (communication_recipient_id)
        REFERENCES school_communication_recipients (id)
        ON DELETE CASCADE;

ALTER TABLE notification_logs
    ADD CONSTRAINT chk_notification_logs_source
        CHECK (
            (access_event_id IS NOT NULL AND communication_recipient_id IS NULL)
            OR
            (access_event_id IS NULL AND communication_recipient_id IS NOT NULL)
        );

CREATE UNIQUE INDEX uk_notification_logs_communication_recipient
    ON notification_logs (communication_recipient_id)
    WHERE communication_recipient_id IS NOT NULL;

CREATE INDEX idx_school_communications_school_created
    ON school_communications (school_id, created_at DESC);

CREATE INDEX idx_school_communications_scheduled
    ON school_communications (status, scheduled_at)
    WHERE status = 'SCHEDULED';

CREATE INDEX idx_communication_recipients_guardian
    ON school_communication_recipients (guardian_id, communication_id);
