CREATE TABLE schools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_app_users_school
        FOREIGN KEY (school_id)
        REFERENCES schools (id),

    CONSTRAINT chk_app_users_role
        CHECK (role IN ('ADMIN', 'OPERATOR'))
);

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    enrollment_number VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(150) NOT NULL,
    grade_name VARCHAR(50),
    group_name VARCHAR(50),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_students_school
        FOREIGN KEY (school_id)
        REFERENCES schools (id),

    CONSTRAINT uk_students_enrollment
        UNIQUE (school_id, enrollment_number)
);

CREATE TABLE guardians (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(30),
    email VARCHAR(150),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_guardians_school
        FOREIGN KEY (school_id)
        REFERENCES schools (id)
);

CREATE TABLE student_guardians (
    student_id BIGINT NOT NULL,
    guardian_id BIGINT NOT NULL,
    relationship VARCHAR(50),
    primary_contact BOOLEAN NOT NULL DEFAULT FALSE,
    receives_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (student_id, guardian_id),

    CONSTRAINT fk_student_guardians_student
        FOREIGN KEY (student_id)
        REFERENCES students (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_student_guardians_guardian
        FOREIGN KEY (guardian_id)
        REFERENCES guardians (id)
        ON DELETE CASCADE
);

CREATE TABLE credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    qr_token VARCHAR(100) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_credentials_student
        FOREIGN KEY (student_id)
        REFERENCES students (id)
        ON DELETE CASCADE
);

CREATE TABLE access_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    credential_id BIGINT,
    event_type VARCHAR(20) NOT NULL,
    capture_method VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recorded_by BIGINT,
    device_name VARCHAR(100),
    notes VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_access_events_student
        FOREIGN KEY (student_id)
        REFERENCES students (id),

    CONSTRAINT fk_access_events_credential
        FOREIGN KEY (credential_id)
        REFERENCES credentials (id),

    CONSTRAINT fk_access_events_user
        FOREIGN KEY (recorded_by)
        REFERENCES app_users (id),

    CONSTRAINT chk_access_events_type
        CHECK (event_type IN ('ENTRY', 'EXIT')),

    CONSTRAINT chk_access_events_method
        CHECK (capture_method IN ('QR_CAMERA', 'QR_USB', 'MANUAL'))
);

CREATE TABLE guardian_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id BIGINT NOT NULL,
    fcm_token TEXT NOT NULL UNIQUE,
    device_name VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ,

    CONSTRAINT fk_guardian_devices_guardian
        FOREIGN KEY (guardian_id)
        REFERENCES guardians (id)
        ON DELETE CASCADE
);

CREATE TABLE notification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    access_event_id BIGINT NOT NULL,
    guardian_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    title VARCHAR(150) NOT NULL,
    message VARCHAR(500) NOT NULL,
    error_message VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMPTZ,

    CONSTRAINT fk_notification_logs_event
        FOREIGN KEY (access_event_id)
        REFERENCES access_events (id),

    CONSTRAINT fk_notification_logs_guardian
        FOREIGN KEY (guardian_id)
        REFERENCES guardians (id),

    CONSTRAINT chk_notification_logs_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX idx_students_school
    ON students (school_id);

CREATE INDEX idx_guardians_school
    ON guardians (school_id);

CREATE INDEX idx_access_events_student
    ON access_events (student_id);

CREATE INDEX idx_access_events_occurred_at
    ON access_events (occurred_at);

CREATE INDEX idx_notification_logs_status
    ON notification_logs (status);