CREATE TABLE guardian_device_enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_guardian_device_enrollments_guardian
        FOREIGN KEY (guardian_id)
        REFERENCES guardians (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_guardian_device_enrollments_expiration
        CHECK (expires_at > created_at),

    CONSTRAINT chk_guardian_device_enrollments_completion
        CHECK (
            used_at IS NULL
            OR revoked_at IS NULL
        )
);

CREATE INDEX idx_guardian_device_enrollments_guardian_active
    ON guardian_device_enrollments (guardian_id)
    WHERE used_at IS NULL
      AND revoked_at IS NULL;