CREATE TABLE academic_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_academic_cycles_school
        FOREIGN KEY (school_id)
        REFERENCES schools (id),

    CONSTRAINT chk_academic_cycles_dates
        CHECK (end_date >= start_date)
);

CREATE UNIQUE INDEX uk_academic_cycles_school_name_ci
    ON academic_cycles (school_id, LOWER(name));

CREATE INDEX idx_academic_cycles_school
    ON academic_cycles (school_id);

CREATE TABLE school_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_cycle_id BIGINT NOT NULL,
    grade_name VARCHAR(50) NOT NULL,
    group_name VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_school_groups_academic_cycle
        FOREIGN KEY (academic_cycle_id)
        REFERENCES academic_cycles (id)
);

CREATE UNIQUE INDEX uk_school_groups_cycle_grade_group_ci
    ON school_groups (
        academic_cycle_id,
        LOWER(grade_name),
        LOWER(group_name)
    );

CREATE INDEX idx_school_groups_academic_cycle
    ON school_groups (academic_cycle_id);

ALTER TABLE students
    ADD COLUMN school_group_id BIGINT;

ALTER TABLE students
    ADD CONSTRAINT fk_students_school_group
        FOREIGN KEY (school_group_id)
        REFERENCES school_groups (id);

CREATE INDEX idx_students_school_group
    ON students (school_group_id);
