ALTER TABLE guardian_device_enrollments
    ADD COLUMN batch_id UUID;

CREATE INDEX idx_guardian_device_enrollments_batch
    ON guardian_device_enrollments (batch_id)
    WHERE batch_id IS NOT NULL;

CREATE TABLE guardian_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id BIGINT NOT NULL,
    guardian_device_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    device_name VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ,

    CONSTRAINT fk_guardian_sessions_guardian
        FOREIGN KEY (guardian_id)
        REFERENCES guardians (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_guardian_sessions_device
        FOREIGN KEY (guardian_device_id)
        REFERENCES guardian_devices (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_guardian_sessions_expiration
        CHECK (expires_at > created_at)
);

CREATE INDEX idx_guardian_sessions_guardian_active
    ON guardian_sessions (guardian_id)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_guardian_sessions_expiration
    ON guardian_sessions (expires_at)
    WHERE revoked_at IS NULL;
